### ISSUE TITLE
use of map with identity has no effect

### ISSUE THREAD

**Issue by ghost** [wvdlaan/todomvc#2]
thank you for this great sample for using quiescent ;-)

this is not a bug but an optimization, if i am right

(map identity ["one" nil "two"]) => (one nil two)

did you mean ?:

(filter identity ["one" nil "two"]) => (one two)

but obviously neither one is needed because of:

(apply str (interpose " " ["one" nil "two"])) => "one two" 

This relates to render.clj:

(defn class-name
  "Convenience function for creating class names from sets. Nils will
not be included."
  [classes](apply str %28interpose " " %28map identity classes))))

**Comment by wvdlaan** [comment]
I'm glad you like the walkthrough. And you are right, the expression can be made much simpler. I changed the code.
